name: polynomial-adaptive-queries
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -O0
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-matches
  - -Wno-name-shadowing
  - -Wno-type-defaults

executables:
  polynomial-adaptive-queries:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
